/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cloudera.sa.simple;  
@SuppressWarnings("all")
/** Hotel Tax Records */
@org.apache.avro.specific.AvroGenerated
public class HotelTaxes extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"HotelTaxes\",\"namespace\":\"com.cloudera.sa.simple\",\"doc\":\"Hotel Tax Records\",\"fields\":[{\"name\":\"tax_payer_number\",\"type\":\"string\"},{\"name\":\"tax_payer_name\",\"type\":[\"null\",\"string\"]},{\"name\":\"tax_payer_address\",\"type\":[\"null\",\"string\"]},{\"name\":\"tax_payer_city\",\"type\":[\"null\",\"string\"]},{\"name\":\"tax_payer_state\",\"type\":[\"null\",\"string\"]},{\"name\":\"tax_payer_zipcode\",\"type\":[\"null\",\"string\"]},{\"name\":\"tax_payer_county\",\"type\":[\"null\",\"string\"]},{\"name\":\"outlet_number\",\"type\":[\"null\",\"int\"]},{\"name\":\"location_name\",\"type\":[\"null\",\"string\"]},{\"name\":\"location_address\",\"type\":[\"null\",\"string\"]},{\"name\":\"location_city\",\"type\":[\"null\",\"string\"]},{\"name\":\"location_state\",\"type\":[\"null\",\"string\"]},{\"name\":\"location_zipcode\",\"type\":[\"null\",\"int\"]},{\"name\":\"location_county\",\"type\":[\"null\",\"string\"]},{\"name\":\"location_room_capacity\",\"type\":[\"null\",\"int\"]},{\"name\":\"location_room_receipts\",\"type\":[\"null\",\"float\"]},{\"name\":\"location_taxable_receipts\",\"type\":[\"null\",\"float\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence tax_payer_number;
  @Deprecated public java.lang.CharSequence tax_payer_name;
  @Deprecated public java.lang.CharSequence tax_payer_address;
  @Deprecated public java.lang.CharSequence tax_payer_city;
  @Deprecated public java.lang.CharSequence tax_payer_state;
  @Deprecated public java.lang.CharSequence tax_payer_zipcode;
  @Deprecated public java.lang.CharSequence tax_payer_county;
  @Deprecated public java.lang.Integer outlet_number;
  @Deprecated public java.lang.CharSequence location_name;
  @Deprecated public java.lang.CharSequence location_address;
  @Deprecated public java.lang.CharSequence location_city;
  @Deprecated public java.lang.CharSequence location_state;
  @Deprecated public java.lang.Integer location_zipcode;
  @Deprecated public java.lang.CharSequence location_county;
  @Deprecated public java.lang.Integer location_room_capacity;
  @Deprecated public java.lang.Float location_room_receipts;
  @Deprecated public java.lang.Float location_taxable_receipts;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public HotelTaxes() {}

  /**
   * All-args constructor.
   */
  public HotelTaxes(java.lang.CharSequence tax_payer_number, java.lang.CharSequence tax_payer_name, java.lang.CharSequence tax_payer_address, java.lang.CharSequence tax_payer_city, java.lang.CharSequence tax_payer_state, java.lang.CharSequence tax_payer_zipcode, java.lang.CharSequence tax_payer_county, java.lang.Integer outlet_number, java.lang.CharSequence location_name, java.lang.CharSequence location_address, java.lang.CharSequence location_city, java.lang.CharSequence location_state, java.lang.Integer location_zipcode, java.lang.CharSequence location_county, java.lang.Integer location_room_capacity, java.lang.Float location_room_receipts, java.lang.Float location_taxable_receipts) {
    this.tax_payer_number = tax_payer_number;
    this.tax_payer_name = tax_payer_name;
    this.tax_payer_address = tax_payer_address;
    this.tax_payer_city = tax_payer_city;
    this.tax_payer_state = tax_payer_state;
    this.tax_payer_zipcode = tax_payer_zipcode;
    this.tax_payer_county = tax_payer_county;
    this.outlet_number = outlet_number;
    this.location_name = location_name;
    this.location_address = location_address;
    this.location_city = location_city;
    this.location_state = location_state;
    this.location_zipcode = location_zipcode;
    this.location_county = location_county;
    this.location_room_capacity = location_room_capacity;
    this.location_room_receipts = location_room_receipts;
    this.location_taxable_receipts = location_taxable_receipts;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tax_payer_number;
    case 1: return tax_payer_name;
    case 2: return tax_payer_address;
    case 3: return tax_payer_city;
    case 4: return tax_payer_state;
    case 5: return tax_payer_zipcode;
    case 6: return tax_payer_county;
    case 7: return outlet_number;
    case 8: return location_name;
    case 9: return location_address;
    case 10: return location_city;
    case 11: return location_state;
    case 12: return location_zipcode;
    case 13: return location_county;
    case 14: return location_room_capacity;
    case 15: return location_room_receipts;
    case 16: return location_taxable_receipts;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tax_payer_number = (java.lang.CharSequence)value$; break;
    case 1: tax_payer_name = (java.lang.CharSequence)value$; break;
    case 2: tax_payer_address = (java.lang.CharSequence)value$; break;
    case 3: tax_payer_city = (java.lang.CharSequence)value$; break;
    case 4: tax_payer_state = (java.lang.CharSequence)value$; break;
    case 5: tax_payer_zipcode = (java.lang.CharSequence)value$; break;
    case 6: tax_payer_county = (java.lang.CharSequence)value$; break;
    case 7: outlet_number = (java.lang.Integer)value$; break;
    case 8: location_name = (java.lang.CharSequence)value$; break;
    case 9: location_address = (java.lang.CharSequence)value$; break;
    case 10: location_city = (java.lang.CharSequence)value$; break;
    case 11: location_state = (java.lang.CharSequence)value$; break;
    case 12: location_zipcode = (java.lang.Integer)value$; break;
    case 13: location_county = (java.lang.CharSequence)value$; break;
    case 14: location_room_capacity = (java.lang.Integer)value$; break;
    case 15: location_room_receipts = (java.lang.Float)value$; break;
    case 16: location_taxable_receipts = (java.lang.Float)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'tax_payer_number' field.
   */
  public java.lang.CharSequence getTaxPayerNumber() {
    return tax_payer_number;
  }

  /**
   * Sets the value of the 'tax_payer_number' field.
   * @param value the value to set.
   */
  public void setTaxPayerNumber(java.lang.CharSequence value) {
    this.tax_payer_number = value;
  }

  /**
   * Gets the value of the 'tax_payer_name' field.
   */
  public java.lang.CharSequence getTaxPayerName() {
    return tax_payer_name;
  }

  /**
   * Sets the value of the 'tax_payer_name' field.
   * @param value the value to set.
   */
  public void setTaxPayerName(java.lang.CharSequence value) {
    this.tax_payer_name = value;
  }

  /**
   * Gets the value of the 'tax_payer_address' field.
   */
  public java.lang.CharSequence getTaxPayerAddress() {
    return tax_payer_address;
  }

  /**
   * Sets the value of the 'tax_payer_address' field.
   * @param value the value to set.
   */
  public void setTaxPayerAddress(java.lang.CharSequence value) {
    this.tax_payer_address = value;
  }

  /**
   * Gets the value of the 'tax_payer_city' field.
   */
  public java.lang.CharSequence getTaxPayerCity() {
    return tax_payer_city;
  }

  /**
   * Sets the value of the 'tax_payer_city' field.
   * @param value the value to set.
   */
  public void setTaxPayerCity(java.lang.CharSequence value) {
    this.tax_payer_city = value;
  }

  /**
   * Gets the value of the 'tax_payer_state' field.
   */
  public java.lang.CharSequence getTaxPayerState() {
    return tax_payer_state;
  }

  /**
   * Sets the value of the 'tax_payer_state' field.
   * @param value the value to set.
   */
  public void setTaxPayerState(java.lang.CharSequence value) {
    this.tax_payer_state = value;
  }

  /**
   * Gets the value of the 'tax_payer_zipcode' field.
   */
  public java.lang.CharSequence getTaxPayerZipcode() {
    return tax_payer_zipcode;
  }

  /**
   * Sets the value of the 'tax_payer_zipcode' field.
   * @param value the value to set.
   */
  public void setTaxPayerZipcode(java.lang.CharSequence value) {
    this.tax_payer_zipcode = value;
  }

  /**
   * Gets the value of the 'tax_payer_county' field.
   */
  public java.lang.CharSequence getTaxPayerCounty() {
    return tax_payer_county;
  }

  /**
   * Sets the value of the 'tax_payer_county' field.
   * @param value the value to set.
   */
  public void setTaxPayerCounty(java.lang.CharSequence value) {
    this.tax_payer_county = value;
  }

  /**
   * Gets the value of the 'outlet_number' field.
   */
  public java.lang.Integer getOutletNumber() {
    return outlet_number;
  }

  /**
   * Sets the value of the 'outlet_number' field.
   * @param value the value to set.
   */
  public void setOutletNumber(java.lang.Integer value) {
    this.outlet_number = value;
  }

  /**
   * Gets the value of the 'location_name' field.
   */
  public java.lang.CharSequence getLocationName() {
    return location_name;
  }

  /**
   * Sets the value of the 'location_name' field.
   * @param value the value to set.
   */
  public void setLocationName(java.lang.CharSequence value) {
    this.location_name = value;
  }

  /**
   * Gets the value of the 'location_address' field.
   */
  public java.lang.CharSequence getLocationAddress() {
    return location_address;
  }

  /**
   * Sets the value of the 'location_address' field.
   * @param value the value to set.
   */
  public void setLocationAddress(java.lang.CharSequence value) {
    this.location_address = value;
  }

  /**
   * Gets the value of the 'location_city' field.
   */
  public java.lang.CharSequence getLocationCity() {
    return location_city;
  }

  /**
   * Sets the value of the 'location_city' field.
   * @param value the value to set.
   */
  public void setLocationCity(java.lang.CharSequence value) {
    this.location_city = value;
  }

  /**
   * Gets the value of the 'location_state' field.
   */
  public java.lang.CharSequence getLocationState() {
    return location_state;
  }

  /**
   * Sets the value of the 'location_state' field.
   * @param value the value to set.
   */
  public void setLocationState(java.lang.CharSequence value) {
    this.location_state = value;
  }

  /**
   * Gets the value of the 'location_zipcode' field.
   */
  public java.lang.Integer getLocationZipcode() {
    return location_zipcode;
  }

  /**
   * Sets the value of the 'location_zipcode' field.
   * @param value the value to set.
   */
  public void setLocationZipcode(java.lang.Integer value) {
    this.location_zipcode = value;
  }

  /**
   * Gets the value of the 'location_county' field.
   */
  public java.lang.CharSequence getLocationCounty() {
    return location_county;
  }

  /**
   * Sets the value of the 'location_county' field.
   * @param value the value to set.
   */
  public void setLocationCounty(java.lang.CharSequence value) {
    this.location_county = value;
  }

  /**
   * Gets the value of the 'location_room_capacity' field.
   */
  public java.lang.Integer getLocationRoomCapacity() {
    return location_room_capacity;
  }

  /**
   * Sets the value of the 'location_room_capacity' field.
   * @param value the value to set.
   */
  public void setLocationRoomCapacity(java.lang.Integer value) {
    this.location_room_capacity = value;
  }

  /**
   * Gets the value of the 'location_room_receipts' field.
   */
  public java.lang.Float getLocationRoomReceipts() {
    return location_room_receipts;
  }

  /**
   * Sets the value of the 'location_room_receipts' field.
   * @param value the value to set.
   */
  public void setLocationRoomReceipts(java.lang.Float value) {
    this.location_room_receipts = value;
  }

  /**
   * Gets the value of the 'location_taxable_receipts' field.
   */
  public java.lang.Float getLocationTaxableReceipts() {
    return location_taxable_receipts;
  }

  /**
   * Sets the value of the 'location_taxable_receipts' field.
   * @param value the value to set.
   */
  public void setLocationTaxableReceipts(java.lang.Float value) {
    this.location_taxable_receipts = value;
  }

  /** Creates a new HotelTaxes RecordBuilder */
  public static com.cloudera.sa.simple.HotelTaxes.Builder newBuilder() {
    return new com.cloudera.sa.simple.HotelTaxes.Builder();
  }
  
  /** Creates a new HotelTaxes RecordBuilder by copying an existing Builder */
  public static com.cloudera.sa.simple.HotelTaxes.Builder newBuilder(com.cloudera.sa.simple.HotelTaxes.Builder other) {
    return new com.cloudera.sa.simple.HotelTaxes.Builder(other);
  }
  
  /** Creates a new HotelTaxes RecordBuilder by copying an existing HotelTaxes instance */
  public static com.cloudera.sa.simple.HotelTaxes.Builder newBuilder(com.cloudera.sa.simple.HotelTaxes other) {
    return new com.cloudera.sa.simple.HotelTaxes.Builder(other);
  }
  
  /**
   * RecordBuilder for HotelTaxes instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<HotelTaxes>
    implements org.apache.avro.data.RecordBuilder<HotelTaxes> {

    private java.lang.CharSequence tax_payer_number;
    private java.lang.CharSequence tax_payer_name;
    private java.lang.CharSequence tax_payer_address;
    private java.lang.CharSequence tax_payer_city;
    private java.lang.CharSequence tax_payer_state;
    private java.lang.CharSequence tax_payer_zipcode;
    private java.lang.CharSequence tax_payer_county;
    private java.lang.Integer outlet_number;
    private java.lang.CharSequence location_name;
    private java.lang.CharSequence location_address;
    private java.lang.CharSequence location_city;
    private java.lang.CharSequence location_state;
    private java.lang.Integer location_zipcode;
    private java.lang.CharSequence location_county;
    private java.lang.Integer location_room_capacity;
    private java.lang.Float location_room_receipts;
    private java.lang.Float location_taxable_receipts;

    /** Creates a new Builder */
    private Builder() {
      super(com.cloudera.sa.simple.HotelTaxes.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.cloudera.sa.simple.HotelTaxes.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tax_payer_number)) {
        this.tax_payer_number = data().deepCopy(fields()[0].schema(), other.tax_payer_number);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.tax_payer_name)) {
        this.tax_payer_name = data().deepCopy(fields()[1].schema(), other.tax_payer_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tax_payer_address)) {
        this.tax_payer_address = data().deepCopy(fields()[2].schema(), other.tax_payer_address);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.tax_payer_city)) {
        this.tax_payer_city = data().deepCopy(fields()[3].schema(), other.tax_payer_city);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.tax_payer_state)) {
        this.tax_payer_state = data().deepCopy(fields()[4].schema(), other.tax_payer_state);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.tax_payer_zipcode)) {
        this.tax_payer_zipcode = data().deepCopy(fields()[5].schema(), other.tax_payer_zipcode);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.tax_payer_county)) {
        this.tax_payer_county = data().deepCopy(fields()[6].schema(), other.tax_payer_county);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.outlet_number)) {
        this.outlet_number = data().deepCopy(fields()[7].schema(), other.outlet_number);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.location_name)) {
        this.location_name = data().deepCopy(fields()[8].schema(), other.location_name);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.location_address)) {
        this.location_address = data().deepCopy(fields()[9].schema(), other.location_address);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.location_city)) {
        this.location_city = data().deepCopy(fields()[10].schema(), other.location_city);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.location_state)) {
        this.location_state = data().deepCopy(fields()[11].schema(), other.location_state);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.location_zipcode)) {
        this.location_zipcode = data().deepCopy(fields()[12].schema(), other.location_zipcode);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.location_county)) {
        this.location_county = data().deepCopy(fields()[13].schema(), other.location_county);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.location_room_capacity)) {
        this.location_room_capacity = data().deepCopy(fields()[14].schema(), other.location_room_capacity);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.location_room_receipts)) {
        this.location_room_receipts = data().deepCopy(fields()[15].schema(), other.location_room_receipts);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.location_taxable_receipts)) {
        this.location_taxable_receipts = data().deepCopy(fields()[16].schema(), other.location_taxable_receipts);
        fieldSetFlags()[16] = true;
      }
    }
    
    /** Creates a Builder by copying an existing HotelTaxes instance */
    private Builder(com.cloudera.sa.simple.HotelTaxes other) {
            super(com.cloudera.sa.simple.HotelTaxes.SCHEMA$);
      if (isValidValue(fields()[0], other.tax_payer_number)) {
        this.tax_payer_number = data().deepCopy(fields()[0].schema(), other.tax_payer_number);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.tax_payer_name)) {
        this.tax_payer_name = data().deepCopy(fields()[1].schema(), other.tax_payer_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tax_payer_address)) {
        this.tax_payer_address = data().deepCopy(fields()[2].schema(), other.tax_payer_address);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.tax_payer_city)) {
        this.tax_payer_city = data().deepCopy(fields()[3].schema(), other.tax_payer_city);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.tax_payer_state)) {
        this.tax_payer_state = data().deepCopy(fields()[4].schema(), other.tax_payer_state);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.tax_payer_zipcode)) {
        this.tax_payer_zipcode = data().deepCopy(fields()[5].schema(), other.tax_payer_zipcode);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.tax_payer_county)) {
        this.tax_payer_county = data().deepCopy(fields()[6].schema(), other.tax_payer_county);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.outlet_number)) {
        this.outlet_number = data().deepCopy(fields()[7].schema(), other.outlet_number);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.location_name)) {
        this.location_name = data().deepCopy(fields()[8].schema(), other.location_name);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.location_address)) {
        this.location_address = data().deepCopy(fields()[9].schema(), other.location_address);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.location_city)) {
        this.location_city = data().deepCopy(fields()[10].schema(), other.location_city);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.location_state)) {
        this.location_state = data().deepCopy(fields()[11].schema(), other.location_state);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.location_zipcode)) {
        this.location_zipcode = data().deepCopy(fields()[12].schema(), other.location_zipcode);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.location_county)) {
        this.location_county = data().deepCopy(fields()[13].schema(), other.location_county);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.location_room_capacity)) {
        this.location_room_capacity = data().deepCopy(fields()[14].schema(), other.location_room_capacity);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.location_room_receipts)) {
        this.location_room_receipts = data().deepCopy(fields()[15].schema(), other.location_room_receipts);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.location_taxable_receipts)) {
        this.location_taxable_receipts = data().deepCopy(fields()[16].schema(), other.location_taxable_receipts);
        fieldSetFlags()[16] = true;
      }
    }

    /** Gets the value of the 'tax_payer_number' field */
    public java.lang.CharSequence getTaxPayerNumber() {
      return tax_payer_number;
    }
    
    /** Sets the value of the 'tax_payer_number' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder setTaxPayerNumber(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.tax_payer_number = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'tax_payer_number' field has been set */
    public boolean hasTaxPayerNumber() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'tax_payer_number' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder clearTaxPayerNumber() {
      tax_payer_number = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'tax_payer_name' field */
    public java.lang.CharSequence getTaxPayerName() {
      return tax_payer_name;
    }
    
    /** Sets the value of the 'tax_payer_name' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder setTaxPayerName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.tax_payer_name = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'tax_payer_name' field has been set */
    public boolean hasTaxPayerName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'tax_payer_name' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder clearTaxPayerName() {
      tax_payer_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'tax_payer_address' field */
    public java.lang.CharSequence getTaxPayerAddress() {
      return tax_payer_address;
    }
    
    /** Sets the value of the 'tax_payer_address' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder setTaxPayerAddress(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.tax_payer_address = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'tax_payer_address' field has been set */
    public boolean hasTaxPayerAddress() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'tax_payer_address' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder clearTaxPayerAddress() {
      tax_payer_address = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'tax_payer_city' field */
    public java.lang.CharSequence getTaxPayerCity() {
      return tax_payer_city;
    }
    
    /** Sets the value of the 'tax_payer_city' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder setTaxPayerCity(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.tax_payer_city = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'tax_payer_city' field has been set */
    public boolean hasTaxPayerCity() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'tax_payer_city' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder clearTaxPayerCity() {
      tax_payer_city = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'tax_payer_state' field */
    public java.lang.CharSequence getTaxPayerState() {
      return tax_payer_state;
    }
    
    /** Sets the value of the 'tax_payer_state' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder setTaxPayerState(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.tax_payer_state = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'tax_payer_state' field has been set */
    public boolean hasTaxPayerState() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'tax_payer_state' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder clearTaxPayerState() {
      tax_payer_state = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'tax_payer_zipcode' field */
    public java.lang.CharSequence getTaxPayerZipcode() {
      return tax_payer_zipcode;
    }
    
    /** Sets the value of the 'tax_payer_zipcode' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder setTaxPayerZipcode(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.tax_payer_zipcode = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'tax_payer_zipcode' field has been set */
    public boolean hasTaxPayerZipcode() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'tax_payer_zipcode' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder clearTaxPayerZipcode() {
      tax_payer_zipcode = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'tax_payer_county' field */
    public java.lang.CharSequence getTaxPayerCounty() {
      return tax_payer_county;
    }
    
    /** Sets the value of the 'tax_payer_county' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder setTaxPayerCounty(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.tax_payer_county = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'tax_payer_county' field has been set */
    public boolean hasTaxPayerCounty() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'tax_payer_county' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder clearTaxPayerCounty() {
      tax_payer_county = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'outlet_number' field */
    public java.lang.Integer getOutletNumber() {
      return outlet_number;
    }
    
    /** Sets the value of the 'outlet_number' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder setOutletNumber(java.lang.Integer value) {
      validate(fields()[7], value);
      this.outlet_number = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'outlet_number' field has been set */
    public boolean hasOutletNumber() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'outlet_number' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder clearOutletNumber() {
      outlet_number = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'location_name' field */
    public java.lang.CharSequence getLocationName() {
      return location_name;
    }
    
    /** Sets the value of the 'location_name' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder setLocationName(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.location_name = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'location_name' field has been set */
    public boolean hasLocationName() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'location_name' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder clearLocationName() {
      location_name = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'location_address' field */
    public java.lang.CharSequence getLocationAddress() {
      return location_address;
    }
    
    /** Sets the value of the 'location_address' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder setLocationAddress(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.location_address = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'location_address' field has been set */
    public boolean hasLocationAddress() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'location_address' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder clearLocationAddress() {
      location_address = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'location_city' field */
    public java.lang.CharSequence getLocationCity() {
      return location_city;
    }
    
    /** Sets the value of the 'location_city' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder setLocationCity(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.location_city = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'location_city' field has been set */
    public boolean hasLocationCity() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'location_city' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder clearLocationCity() {
      location_city = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'location_state' field */
    public java.lang.CharSequence getLocationState() {
      return location_state;
    }
    
    /** Sets the value of the 'location_state' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder setLocationState(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.location_state = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'location_state' field has been set */
    public boolean hasLocationState() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'location_state' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder clearLocationState() {
      location_state = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'location_zipcode' field */
    public java.lang.Integer getLocationZipcode() {
      return location_zipcode;
    }
    
    /** Sets the value of the 'location_zipcode' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder setLocationZipcode(java.lang.Integer value) {
      validate(fields()[12], value);
      this.location_zipcode = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'location_zipcode' field has been set */
    public boolean hasLocationZipcode() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'location_zipcode' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder clearLocationZipcode() {
      location_zipcode = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'location_county' field */
    public java.lang.CharSequence getLocationCounty() {
      return location_county;
    }
    
    /** Sets the value of the 'location_county' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder setLocationCounty(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.location_county = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'location_county' field has been set */
    public boolean hasLocationCounty() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'location_county' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder clearLocationCounty() {
      location_county = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'location_room_capacity' field */
    public java.lang.Integer getLocationRoomCapacity() {
      return location_room_capacity;
    }
    
    /** Sets the value of the 'location_room_capacity' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder setLocationRoomCapacity(java.lang.Integer value) {
      validate(fields()[14], value);
      this.location_room_capacity = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'location_room_capacity' field has been set */
    public boolean hasLocationRoomCapacity() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'location_room_capacity' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder clearLocationRoomCapacity() {
      location_room_capacity = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'location_room_receipts' field */
    public java.lang.Float getLocationRoomReceipts() {
      return location_room_receipts;
    }
    
    /** Sets the value of the 'location_room_receipts' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder setLocationRoomReceipts(java.lang.Float value) {
      validate(fields()[15], value);
      this.location_room_receipts = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'location_room_receipts' field has been set */
    public boolean hasLocationRoomReceipts() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'location_room_receipts' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder clearLocationRoomReceipts() {
      location_room_receipts = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'location_taxable_receipts' field */
    public java.lang.Float getLocationTaxableReceipts() {
      return location_taxable_receipts;
    }
    
    /** Sets the value of the 'location_taxable_receipts' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder setLocationTaxableReceipts(java.lang.Float value) {
      validate(fields()[16], value);
      this.location_taxable_receipts = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'location_taxable_receipts' field has been set */
    public boolean hasLocationTaxableReceipts() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'location_taxable_receipts' field */
    public com.cloudera.sa.simple.HotelTaxes.Builder clearLocationTaxableReceipts() {
      location_taxable_receipts = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    @Override
    public HotelTaxes build() {
      try {
        HotelTaxes record = new HotelTaxes();
        record.tax_payer_number = fieldSetFlags()[0] ? this.tax_payer_number : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.tax_payer_name = fieldSetFlags()[1] ? this.tax_payer_name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.tax_payer_address = fieldSetFlags()[2] ? this.tax_payer_address : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.tax_payer_city = fieldSetFlags()[3] ? this.tax_payer_city : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.tax_payer_state = fieldSetFlags()[4] ? this.tax_payer_state : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.tax_payer_zipcode = fieldSetFlags()[5] ? this.tax_payer_zipcode : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.tax_payer_county = fieldSetFlags()[6] ? this.tax_payer_county : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.outlet_number = fieldSetFlags()[7] ? this.outlet_number : (java.lang.Integer) defaultValue(fields()[7]);
        record.location_name = fieldSetFlags()[8] ? this.location_name : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.location_address = fieldSetFlags()[9] ? this.location_address : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.location_city = fieldSetFlags()[10] ? this.location_city : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.location_state = fieldSetFlags()[11] ? this.location_state : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.location_zipcode = fieldSetFlags()[12] ? this.location_zipcode : (java.lang.Integer) defaultValue(fields()[12]);
        record.location_county = fieldSetFlags()[13] ? this.location_county : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.location_room_capacity = fieldSetFlags()[14] ? this.location_room_capacity : (java.lang.Integer) defaultValue(fields()[14]);
        record.location_room_receipts = fieldSetFlags()[15] ? this.location_room_receipts : (java.lang.Float) defaultValue(fields()[15]);
        record.location_taxable_receipts = fieldSetFlags()[16] ? this.location_taxable_receipts : (java.lang.Float) defaultValue(fields()[16]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
